// <auto-generated />
using System;
using Barbu.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Barbu.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BarbuDbContext))]
    partial class BarbuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Barbu.Domain.Entities.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengedGamePlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengerGamePlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointsTransferred")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreDifference")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChallengedGamePlayerId");

                    b.HasIndex("ChallengerGamePlayerId");

                    b.HasIndex("DealId", "ChallengerGamePlayerId", "ChallengedGamePlayerId")
                        .IsUnique();

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.Championship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Championships");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.ChampionshipPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChampionshipId")
                        .HasColumnType("uuid");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalPoints")
                        .HasPrecision(10, 1)
                        .HasColumnType("numeric(10,1)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ChampionshipId", "PlayerId")
                        .IsUnique();

                    b.ToTable("ChampionshipPlayers");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContractType")
                        .HasColumnType("integer");

                    b.Property<int>("DealNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeclarerGamePlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeclarerGamePlayerId");

                    b.HasIndex("GameId", "DealNumber")
                        .IsUnique();

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.DealScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid");

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("GamePlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScoreDetails")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("GamePlayerId");

                    b.HasIndex("DealId", "GamePlayerId")
                        .IsUnique();

                    b.ToTable("DealScores");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChampionshipId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentDealNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId");

                    b.HasIndex("Status");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.GamePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingChallenges")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingSurcontres")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("GameId", "Position")
                        .IsUnique();

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.Challenge", b =>
                {
                    b.HasOne("Barbu.Domain.Entities.GamePlayer", "Challenged")
                        .WithMany()
                        .HasForeignKey("ChallengedGamePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Barbu.Domain.Entities.GamePlayer", "Challenger")
                        .WithMany()
                        .HasForeignKey("ChallengerGamePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Barbu.Domain.Entities.Deal", "Deal")
                        .WithMany("Challenges")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenged");

                    b.Navigation("Challenger");

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.ChampionshipPlayer", b =>
                {
                    b.HasOne("Barbu.Domain.Entities.Championship", "Championship")
                        .WithMany("ChampionshipPlayers")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Barbu.Domain.Entities.Player", "Player")
                        .WithMany("ChampionshipPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Championship");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.Deal", b =>
                {
                    b.HasOne("Barbu.Domain.Entities.GamePlayer", "Declarer")
                        .WithMany("DeclaredDeals")
                        .HasForeignKey("DeclarerGamePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Barbu.Domain.Entities.Game", "Game")
                        .WithMany("Deals")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declarer");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.DealScore", b =>
                {
                    b.HasOne("Barbu.Domain.Entities.Deal", "Deal")
                        .WithMany("DealScores")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Barbu.Domain.Entities.GamePlayer", "GamePlayer")
                        .WithMany()
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Deal");

                    b.Navigation("GamePlayer");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.Game", b =>
                {
                    b.HasOne("Barbu.Domain.Entities.Championship", "Championship")
                        .WithMany("Games")
                        .HasForeignKey("ChampionshipId");

                    b.Navigation("Championship");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.GamePlayer", b =>
                {
                    b.HasOne("Barbu.Domain.Entities.Game", "Game")
                        .WithMany("GamePlayers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Barbu.Domain.Entities.Player", "Player")
                        .WithMany("GamePlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.Championship", b =>
                {
                    b.Navigation("ChampionshipPlayers");

                    b.Navigation("Games");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.Deal", b =>
                {
                    b.Navigation("Challenges");

                    b.Navigation("DealScores");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.Game", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("GamePlayers");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.GamePlayer", b =>
                {
                    b.Navigation("DeclaredDeals");
                });

            modelBuilder.Entity("Barbu.Domain.Entities.Player", b =>
                {
                    b.Navigation("ChampionshipPlayers");

                    b.Navigation("GamePlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
